version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Installing test dependencies..."
      - cd app
      - npm install
      - echo "Dependencies installed"
  build:
    commands:
      #- echo "Starting build process..."
      #- echo "Running unit tests..."
      #- npm run test
      #- echo "Unit test finished."
      #- cd ..
      - echo "Building template...."
      - sam build -t $BUILD_TEMPLATE --use-container
      - sam package -t .aws-sam/build/template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
      - echo "Template created successfully."
      - echo "Build process finished."
artifacts:
  files:
    - .aws-sam/build/template.yaml
    - outputtemplate.yml